//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATO
    {
        public int idcontrato { get; set; }
        public int idanuncio { get; set; }
        public int idusuario { get; set; }
        public int finalizado { get; set; }
    
        public virtual ANUNCIO ANUNCIO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
